workflows:
  android-workflow:
    name: Comparte App Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.android.app"
        APP_URL: "https://comparte.vercel.app/"
      node: latest
      npm: 6
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
      - name: Add Android platform
        script: |
          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android release
        script: |
          echo $KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cordova build android --release --no-interactive --prod --device
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "/tmp/keystore.keystore" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - carlosespinoza526@gmail.com
        notify:
          success: true
          failure: true
