workflows:
  android-workflow:
    name: Comparte App Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.android.app"
        APP_URL: "https://comparte.vercel.app/"
        ANDROID_HOME: "/usr/local/share/android-sdk"
        ANDROID_SDK_ROOT: "/usr/local/share/android-sdk"
        PATH: "$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
      node: latest
      npm: 6
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Setup Android SDK environment
        script: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "PATH=$PATH"
          sdkmanager --version || echo "sdkmanager not found"
      - name: Install Android Build Tools
        script: |
          sdkmanager "build-tools;35.0.0"
      - name: Install dependencies
        script: |
          npm install
          npm ci
      - name: Add Android platform
        script: |
          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android release
        script: |
          echo $KEYSTORE | base64 -d > /tmp/keystore.keystore
          cordova build android --release --no-interactive --prod --device
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA256withRSA -digestalg SHA-256 -keystore "/tmp/keystore.keystore" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - electronicnoise185@gmail.com
        notify:
          success: true
          failure: true
